export interface Coches {
  marca: string;
  modelos: string[];
}

export const COLORES = [
  'blanco',
  'negro',
  'rojo',
  'amarillo',
  'verde',
  'gris',
  'dorado',
  'marron',
  'morado',
  'beige',
  'perla',
  'otro',
];

export const COLOURS = [
  'white',
  'black',
  'red',
  'yellow',
  'green',
  'gray',
  'gold',
  'brown',
  'purple',
  'beige',
  'pearl',
  'perla',
  'other',
];

export const CARS: Coches[] = [
  {
    marca: 'Alfa-Romeo',
    modelos: [
      'Giulietta',
      'MiTo',
      'Junior Elettrica',
      '4C',
      'Tonale',
      'Giulia',
      'Stelvia',
      'Otro modelo',
    ],
  },
  {
    marca: 'Seat',
    modelos: [
      'Alhambra',
      'Arona',
      'Ateca',
      'Ibiza',
      'Leon',
      'MII',
      'Nuevo-León',
      'Mó',
      'Terraco',
      'Toledo',
      'Otro modelo',
    ],
  },
  {
    marca: 'Citroen',
    modelos: [
      'C5',
      'AMI',
      'Berlingo',
      'C-Elysée',
      'C-Zero',
      'C1',
      'C3',
      'C3 AirCross',
      'C4',
      'C4 Cactus',
      'C4X',
      'C5 Aircross',
      'C5-X',
      'Grand c4 Space Tourer',
      'Jumpy',
      'SpaceTourer',
      'SUV C5 Aircross Hybrid',
      'Otro modelo',
    ],
  },
  {
    marca: 'Cupra',
    modelos: [
      'Ateca',
      'Born',
      'Formentor',
      'León',
      'Tavascar',
      'Terramar',
      'Otro modelo',
    ],
  },
  {
    marca: 'Dacia',
    modelos: [
      'Dokker',
      'Duster',
      'Lodgy',
      'Bigster',
      'Jogger',
      'Logan',
      'Sandero',
      'Spring',
      'Otro modelo',
    ],
  },
  {
    marca: 'Fiat',
    modelos: [
      '500',
      '501',
      '502',
      'Doblò',
      'Ducato',
      'Fiorino',
      'Panda-Van',
      'Qubo',
      'Squdo',
      'Talento',
      'Tipo',
      'Topolino',
      'Otro modelo',
    ],
  },
  {
    marca: 'Volkswagen',
    modelos: [
      'Arteon',
      'Golf',
      'Multivan',
      'Passat',
      'Polo',
      'Taigo',
      'Tiguan',
      'T-Cross',
      'T-Roc',
      'Tuareg',
      'Touran',
      'Otro modelo',
    ],
  },
  {
    marca: 'Renault',
    modelos: [
      'Arkana',
      'Austral',
      'Captur',
      'Clio',
      'Espace',
      'Gran-Scenic',
      'Kadjar',
      'Kangoo',
      'Megane',
      'Trafic',
      'Twingo',
      'Zoe',
      'Otro modelo',
    ],
  },
  {
    marca: 'Peugeot',
    modelos: [
      '108',
      '208',
      '308',
      '408',
      '508',
      '2008',
      '3008',
      '5008',
      'Boxer',
      'Expert',
      'Traveller',
      'Rifter',
      'Partner',
      'Otro modelo',
    ],
  },
  {
    marca: 'Ford',
    modelos: [
      'Capri',
      'Edge',
      'E-Transit',
      'Ecosport',
      'Explorer',
      'Fiesta',
      'Focus',
      'Kuga',
      'Mustang',
      'Puma',
      'Mondeo',
      'Tourneo',
      'Otro modelo',
    ],
  },
  {
    marca: 'Toyota',
    modelos: [
      'Auris',
      'Aygo',
      'Corolla',
      'Highlander',
      'Hilux',
      'Land Cruiser',
      'Mirai',
      'Prius',
      'Proace',
      'RAV4',
      'Yaris',
      'Otro modelo',
    ],
  },
  {
    marca: 'BMW',
    modelos: [
      'Serie 1',
      'Serie 2',
      'Serie 3',
      'Serie 4',
      'Serie 5',
      'Serie 7',
      'I',
      'M',
      'X',
      'Z',
      'Otro modelo',
    ],
  },
  {
    marca: 'Audi',
    modelos: [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'Q2',
      'Q3',
      'Q4',
      'Q5',
      'S5',
      'Q7',
      'Q8',
      'R8-Coupé',
      'R8-Spyder',
      'RS-3',
      'RS-4',
      'RS-5',
      'RS-6',
      'RS-7',
      'RS-Q3',
      'RS-Q8',
      'S3',
      'S4',
      'S5',
      'S6',
      'S7',
      'S8',
      'TT-Coupé',
      'TT-Roadster',
      'Otro modelo',
    ],
  },
  {
    marca: 'Mercedes-Benz',
    modelos: [
      'A-Class',
      'B-Class',
      'C-Class',
      'E-Class',
      'G-Class',
      'S-Class',
      'T-Class',
      'V-Class',
      'CLE',
      'EQA',
      'EQS',
      'EQV',
      'eCitan',
      'eSprinter',
      'GLA',
      'GLC',
      'GLE',
      'GLS',
      'Marco-Polo',
      'Vito',
      'Otro modelo',
    ],
  },
  {
    marca: 'Honda',
    modelos: [
      'CIVIC',
      'CR-V',
      'e:Ny1',
      'HONDA',
      'HR-V',
      'JAZZ',
      'ZR-V',
      'Otro modelo',
    ],
  },
  {
    marca: 'Hyundai',
    modelos: [
      'Bayon',
      'i10',
      'i20',
      'i30',
      'Inster',
      'Ionic',
      'Kona',
      'Nexo',
      'Santa Fe',
      'Staria',
      'Tucson',
      'Otro modelo',
    ],
  },
  {
    marca: 'Kia',
    modelos: [
      'Ceed',
      'EV-3',
      'EV-6',
      'EV-9',
      'e-Soul',
      'Niro',
      'Picanto',
      'Proceed',
      'Rio',
      'Sorento',
      'Sportage',
      'Stinger',
      'Stonic',
      'XCEED',
      'Otro modelo',
    ],
  },
  {
    marca: 'Land-Rover',
    modelos: ['Discovery', 'Range', 'Otro modelo'],
  },
  {
    marca: 'Lexus',
    modelos: [
      'CT 200h',
      'ES 300h',
      'IS 300h',
      'LBX',
      'LC 500',
      'LC CV',
      'LM 350h',
      'LS 500h',
      'NX 300h',
      'NX 350',
      'NX 450',
      'RC 300h',
      'RC F',
      'RX 350h',
      'RX 450h',
      'RX 500h',
      'RZ 300e',
      'RZ 450e',
      'UX 250h',
      'UX 300E',
      'UX 300h',
      'Otro modelo',
    ],
  },
  {
    marca: 'Mazda',
    modelos: [
      'Mazda2',
      'Mazda3',
      'Mazda6',
      'CX-3',
      'CX-30',
      'CX-5',
      'CX-60',
      'CX-80',
      'MX-5',
      'MX-30',
      'Otro modelo',
    ],
  },
  {
    marca: 'Nissan',
    modelos: [
      '370Z',
      'ARIYA',
      'eNV200',
      'GT-R',
      'JUKE',
      'LEAF',
      'Micra',
      'Nuevo Ayira',
      'Nuevo Qashqai',
      'Nuevo X-Trail',
      'NV250',
      'NV300',
      'NV400',
      'Primastar',
      'Qashqai',
      'TOWNSTAR',
      'X-Trail',
      'Otro modelo',
    ],
  },
  {
    marca: 'Opel',
    modelos: [
      'Astra',
      'Combo',
      'Corsa',
      'Crossland',
      'Insignia',
      'Moka',
      'Movano',
      'Vivar',
      'Zafira',
      'Otro modelo',
    ],
  },
  {
    marca: 'Otra',
    modelos: ['Otro'],
  },
];
