"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 0e36c03c39e4
Revises: dc4d2a8ca403
Create Date: 2025-02-13 19:46:37.935371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e36c03c39e4'
down_revision = 'dc4d2a8ca403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_viaje', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hora_llegada', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('duracion_viaje', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajes', schema=None) as batch_op:
        batch_op.drop_column('duracion_viaje')
        batch_op.drop_column('hora_llegada')
        batch_op.drop_column('precio_viaje')

    # ### end Alembic commands ###
