"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 1b0f836fd934
Revises: 55b92d3b9b33
Create Date: 2025-02-03 13:07:29.126855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0f836fd934'
down_revision = '55b92d3b9b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('plazas', sa.Integer(), nullable=False),
    sa.Column('hora_salida', sa.String(length=5), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('ruta_seleccionada', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viajes')
    # ### end Alembic commands ###
