"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 55b92d3b9b33
Revises: 2238dd9ced2d
Create Date: 2025-02-03 12:57:32.419044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b92d3b9b33'
down_revision = '2238dd9ced2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_nacimiento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_nacimiento')

    # ### end Alembic commands ###
