"""Corregir relaciones con claves foráneas ambiguas

Revision ID: 5896e54a2997
Revises: 
Create Date: 2025-02-12 13:05:12.267964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5896e54a2997'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('orientacion', sa.String(length=50), nullable=False),
    sa.Column('pronombre', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('biografia', sa.String(length=500), nullable=True),
    sa.Column('fotoPerfil', sa.String(length=250), nullable=True),
    sa.Column('preferencias', sa.String(length=50), nullable=False),
    sa.Column('rolPerfil', sa.String(length=50), nullable=False),
    sa.Column('carnet_conducir_verificado', sa.Boolean(), nullable=True),
    sa.Column('numero_carnet_conducir', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento_carnet', sa.Date(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('monederos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('puntuaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], name='fk_puntuacion_evaluador'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='fk_puntuacion_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('viajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=100), nullable=False),
    sa.Column('plazas', sa.Integer(), nullable=False),
    sa.Column('hora_salida', sa.String(length=5), nullable=False),
    sa.Column('fecha_salida', sa.DateTime(), nullable=False),
    sa.Column('ruta_seleccionada', sa.JSON(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viajes')
    op.drop_table('vehiculos')
    op.drop_table('puntuaciones')
    op.drop_table('monederos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
