"""Initial migration

Revision ID: f67396743915
Revises: 3fad055e7b81
Create Date: 2025-01-15 11:57:10.743245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67396743915'
down_revision = '3fad055e7b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=250), nullable=False))
        batch_op.drop_column('apellido_dos')
        batch_op.drop_column('apellido_uno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_uno', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('apellido_dos', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
